### ISSUE TITLE
show abnormality with 174x100 yuv data

### ISSUE THREAD

**Issue by douzhongqiang** [MasterAler/SampleYUVRenderer#1]
show abnormality with 174x100 yuv data.

**Comment by MasterAler** [comment]
Sorry for such a long time to answer, was quite busy recently.
Could you, please, provide some sample data or source, where I could check and debug the problem?

**Comment by douzhongqiang** [comment]
I have found a solution

add the following code before glTexImage2D

glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
glPixelStorei(GL_UNPACK_SKIP_PIXELS, 0);
glPixelStorei(GL_UNPACK_SKIP_ROWS, 0);

**Comment by MasterAler** [comment]
Thanks! Done.
