### ISSUE TITLE
Hello, with respect to 

### ISSUE THREAD

**Issue by leeyunhome** [MasterAler/SampleYUVRenderer#3]
Thank you first.

I have a question about the license for this program.
I want to use this source code in a commercial program, is it possible?

Thank you for posting a good program.

**Comment by MasterAler** [comment]
Hello!

Glad to hear that my small piece of code got to be useful =)
Sure, you can do whatever you like with it, I've added a permissive license to make it definite.

Feel free to report if any bugs occur while using the sources!
